version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sign-app
  
  python-app:
    build:
      context: ./sign-detection-api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./sign-detection-api:/app
    environment:
      - FLASK_ENV=development
