const APP_USER_TYPES = {
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
};

const APP_PERMISSION = {
  READ: 18906,
  DELETE: 18908,
  UPDATE: 18909,
  CREATE: 18910,
};

export { APP_PERMISSION, APP_USER_TYPES };
