name: Master Workflow - Build and deploy Towy Backoffice

on:
  push:
    branches: [ "master" ]

jobs:
  build-react-app:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: install packages
      run: npm install
    - name: build app
      run: npm run build:development
    - name: Configure AWS Creadentails
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: us-east-1
    - name: Deploy react app
      run: aws s3 sync ./build s3://towy-bo-dev.layoutindex.dev
